### ISSUE TITLE
[BUG]Action fails to find unprotected branches when Rulesets are applied

### ISSUE THREAD

**Issue by vizeit** [crs-k/stale-branches#1061]
**Describe the bug**
When Rulesets are applied on the repository that enforces metadata restriction, this action fails to find / list unprotected branches even though they are present in the repo

**To Reproduce**
1. Ensure that there is at least one unprotected branch e.g. test-123
2. Go to Rules -> Rulesets and add a rule 'branch-name' to enforce the branch name format 
    Metadata restriction -> branch name -> must match regex pattern -> ^(test|TEST)-[0-9]+$
    Also, make sure protected branch names are bypassed in target branch list and ensure that no check boxes under branch protection are set for the ruleset 'branch-name'
4. Configure Github action with a step to use this Action 'stale-branches'
5. Observe that actions fails to list any branches even though unprotected branch is present
6. If you remove the ruleset from step 2 and run this action, it finds/lists the unprotected branches

**Expected behavior**
This action should be able to list and process unprotected branches even with Rulesets just for the metadata restriction

**Additional context**
The list branches API response includes additional details about the protection. It might be required to list the branches without 'protected' query parameter false but rather not passing the protected query parameter and using the 'protection' attribute in the response

```
[  
  {
    "name": "main",
    "commit": {
      "sha": "21a12ddccac08e1c4e0477d2a3ee19038876d456",
      "url": "https://api.github.com/repos/testowner/testrepo/commits/21a12ddccac08e1c4e0477d2a3ee19038876d456"
    },
    "protected": true,
    "protection": {
      "enabled": true,
      "required_status_checks": {
        "enforcement_level": "off",
        "contexts": [],
        "checks": []
      }
    },
    "protection_url": "https://api.github.com/repos/testowner/testrepo/branches/main/protection"
  },
  {
    "name": "test-123",
    "commit": {
      "sha": "601b5cc53cb0a9a5780dc95deeed38ec333e6d33",
      "url": "https://api.github.com/repos/testowner/testrepo/commits/601b5cc53cb0a9a5780dc95deeed38ec333e6d33"
    },
    "protected": true,
    "protection": {
      "enabled": false,
      "required_status_checks": {
        "enforcement_level": "off",
        "contexts": [],
        "checks": []
      }
    },
    "protection_url": "https://api.github.com/repos/testowner/testrepo/branches/test-123/protection"
  }
]
```

Note: Also opened a Github support ticket for the list branches API behavior

**Comment by uladzislau-orlovskiy** [comment]
Issue is still relevant. @crs-k any plans to fix that?

**Comment by uladzislau-orlovskiy** [comment]
had created PR. not sure what I am doing. @crs-k would you mind take a look?

**Comment by crs-k** [comment]
hey there @uladzislau-orlovskiy , i had to revert your PR after taking a closer look. by removed `protected: false` and adding in the snippet suggested above, all branches are returned in scope, including `main` and other branches with explicit protections defined.

in recreating the behavior outlined by @vizeit, i do see that `protected: false` will remove a branch with any ruleset applied to it from scope. i am assuming github treats all branches in a ruleset's scope to be protected by the `enforcement` field. unfortunately, implementing the proposed solution pulls all branches into scope despite protections being enabled, this could cause serious issues for teams with long-lived feature branches for example.

i am open to testing other approaches.

**Comment by vizeit** [comment]
Based on the reply from GitHub support (mentioned in my previous comment), protection.enabled field should be used to check for any protected branch. I am not sure how using that field will also return protected branches with unprotected branches for your stale branch logic. In my understanding, GitHub is moving towards Rulesets and more and more users of this action will run into the same issue

**Comment by uladzislau-orlovskiy** [comment]
> hey there @uladzislau-orlovskiy , i had to revert your PR after taking a closer look. by removing `protected: false` and adding in the snippet suggested above, all branches are returned in scope, including `main` and other branches with explicit protections defined.
> 
> in recreating the behavior outlined by @vizeit, i do see that `protected: false` will remove a branch with any ruleset applied to it from scope. i am assuming github treats all branches in a ruleset's scope to be protected by the `enforcement` field. unfortunately, implementing the proposed solution pulls all branches into scope despite protections being enabled, this could cause serious issues for teams with long-lived feature branches for example.
> 
> i am open to testing other approaches.
speaking of other approaches. how can I test this project localy? I am happy to troubleshoot it and test things localy.

**Comment by uladzislau-orlovskiy** [comment]
> hey there @uladzislau-orlovskiy , i had to revert your PR after taking a closer look. by removing `protected: false` and adding in the snippet suggested above, all branches are returned in scope, including `main` and other branches with explicit protections defined.
> 
> in recreating the behavior outlined by @vizeit, i do see that `protected: false` will remove a branch with any ruleset applied to it from scope. i am assuming github treats all branches in a ruleset's scope to be protected by the `enforcement` field. unfortunately, implementing the proposed solution pulls all branches into scope despite protections being enabled, this could cause serious issues for teams with long-lived feature branches for example.
> 
> i am open to testing other approaches.

can we just use the following endpoint during deletion? /repos/OWNER/REPO/branches/BRANCH/protection 
it can return 

`
  "allow_deletions": {
    "enabled": false
  },
`

**Comment by crs-k** [comment]
> > hey there @uladzislau-orlovskiy , i had to revert your PR after taking a closer look. by removing `protected: false` and adding in the snippet suggested above, all branches are returned in scope, including `main` and other branches with explicit protections defined.
> 
> > 
> 
> > in recreating the behavior outlined by @vizeit, i do see that `protected: false` will remove a branch with any ruleset applied to it from scope. i am assuming github treats all branches in a ruleset's scope to be protected by the `enforcement` field. unfortunately, implementing the proposed solution pulls all branches into scope despite protections being enabled, this could cause serious issues for teams with long-lived feature branches for example.
> 
> > 
> 
> > i am open to testing other approaches.
> 
> 
> 
> can we just use the following endpoint during filtering? /repos/OWNER/REPO/branches/BRANCH/protection 
> 
> it can return 
> 
> 
> 
> `
> 
>   "allow_deletions": {
> 
>     "enabled": false
> 
>   },
> 
> `

The issue with that approach is that we would create issues on protected branches that do not have that flag set to false. I will take a look at the endpoint when I have time and see if we can mimic the current scope, but include branches scoped by rulesets.

**Comment by uladzislau-orlovskiy** [comment]
> > > hey there @uladzislau-orlovskiy , i had to revert your PR after taking a closer look. by removing `protected: false` and adding in the snippet suggested above, all branches are returned in scope, including `main` and other branches with explicit protections defined.
> > 
> > 
> > > 
> > 
> > 
> > > in recreating the behavior outlined by @vizeit, i do see that `protected: false` will remove a branch with any ruleset applied to it from scope. i am assuming github treats all branches in a ruleset's scope to be protected by the `enforcement` field. unfortunately, implementing the proposed solution pulls all branches into scope despite protections being enabled, this could cause serious issues for teams with long-lived feature branches for example.
> > 
> > 
> > > 
> > 
> > 
> > > i am open to testing other approaches.
> > 
> > 
> > can we just use the following endpoint during filtering? /repos/OWNER/REPO/branches/BRANCH/protection
> > it can return
> > `
> > "allow_deletions": {
> > ```
> > "enabled": false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > },
> > `
> 
> The issue with that approach is that we would create issues on protected branches that do not have that flag set to false. I will take a look at the endpoint when I have time and see if we can mimic the current scope, but include branches scoped by rulesets.

we can do it other way. when branch is not protected this endpoint gives the following:

from gh api /repos/OWNER/REPO/branches/BRANCH/protection
`
gh: Branch not protected (HTTP 404)
{
  "message": "Branch not protected",
  "documentation_url": "https://docs.github.com/rest/branches/branch-protection#get-branch-protection"
}
`
