### ISSUE TITLE
Verified creator flag in GitHub Marketplace

### ISSUE THREAD

**Issue by nicovama** [crs-k/stale-branches#1274]
Hello guys.

Would it be possible to makefpicalausa/remove-stale-branches marked as "Verified creator" in GitHub Marketplace please?

Example (https://github.com/marketplace/actions/renovate-bot-github-action):
![image](https://github.com/user-attachments/assets/28ef9e9b-d2af-4446-a619-575c8e49c8d4)

Here are the docs on how to do [this](https://docs.github.com/en/apps/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization) and the [online submission form](https://partner.github.com/technology-partners#form-signUp).

**Comment by crs-k** [comment]
Hey @nicovama, I don't believe I can do this on a personal account. Is this preventing something?
