### ISSUE TITLE
[FEATURE] Allow deletion of specific protected branches

### ISSUE THREAD

**Issue by MattMencel** [crs-k/stale-branches#905]
**Is your feature request related to a problem? Please describe.**

I would like to be able to delete stale protected branches.

**Describe the solution you'd like**

Allow deletion of protected branches when the [Allow Deletions](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#allow-deletions) option is enabled.

Or via a new Action Input. Maybe `stale-branches-filter-regex`.

**Describe alternatives you've considered**

Deleting branch protection rules, but this is not really an alternative. Branch protection rules are there for a reason for newer branches, but on old branches I am ok deleting them when Allow deletions is enabled.

**Additional context**

**Comment by crs-k** [comment]
I think this is feasible. Currently, I exclude all protected branches when pulling the list from the repo, but let me see if the package allows to filter on the field you linked instead, otherwise it may take some work.

**Comment by crs-k** [comment]
Looks like this may be more complicated than I hoped. For reference, I use [this call](https://docs.github.com/en/rest/branches/branches?apiVersion=2022-11-28#list-branches) to pull branches and filter protected ones to avoid creating issues that cannot be resolved. https://github.com/crs-k/stale-branches/blob/c5a00439b33c95f7e826c5f4f9b4eb74c850f1fa/src/functions/get-branches.ts#L16

it looks like to make this work, I'd need to pull all branches then filter out protected ones that do not allow for deletion using [this call](https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#get-branch-protection). My work and personal life don't currently have enough time for me to write this safely or quickly, but if anyone wants to take a shot and submit a PR I can help from there.

**Comment by ecimionatto** [comment]
Prune branches with branch protection rulesets is needed when want to enforce other policies such as requiring signed commits (achievable through branch rulesets).
