### ISSUE TITLE
[FEATURE] Max operations per run

### ISSUE THREAD

**Issue by IOrlandoni** [crs-k/stale-branches#925]
**Is your feature request related to a problem? Please describe.**
Running the action is a bit of a gamble on the rate limit, since we can only control it by the number of issues, it's unclear how many operations will use.

**Describe the solution you'd like**
Same as stalebot for PRs: "[operations-per-run](https://github.com/actions/stale#operations-per-run)" to be respected by the action and stop when reached (or close to, as to not leave half-done things).

**Describe alternatives you've considered**
Utilizing the number the 'max-issues', but that doesn't achieve the same thing.

**Additional context**

**Comment by fredw** [comment]
I have exactly the same issue. I introduced the action in a repository that had `400+` branches and we often reach the GitHub API rate limit 😬 .

**Comment by crs-k** [comment]
There is a rate limit check in place to exit if the action consumes 95% of your quota. Have you found this is not working? Or are you looking for a more configurable limit? I could make that percentage an input to accomplish this.

**Comment by crs-k** [comment]
https://github.com/crs-k/stale-branches/blob/c46e743c734383097c98ed416499b4ff1cd03d85/src/stale-branches.ts#L46

for reference

**Comment by fredw** [comment]
@crs-k, thanks for sharing the reference, and good to hear we have such limits. I didn't know the error was coming from the Action itself but rather from the GH API.

I think the problem then is we set the run as `failed`. 
Shouldn't we instead just stop running without producing any errors? If we check the [github.com/actions/stale](https://github.com/actions/stale) (which I personally also use together with `crs-k/stale-branches`), specifically the [operations-per-run](https://github.com/actions/stale#operations-per-run) settings, if the limit is reached the action simply stops running without any error. I think we should do the same here.

**Comment by crs-k** [comment]
After looking this over, I still prefer the percentage usage check on the rate limit. Since different types of accounts will have an extreme range of operations in their rate limit, defaulting this would be difficult, where the percentage check works regardless.

**Comment by fredw** [comment]
@crs-k I wasn't challenging the current settings we have at the moment, but rather the way the limit is reported.
If you think this is unrelated to the current issue, I can open another one. But I still don't think we should fail the run because the limit was reached.
