### ISSUE TITLE
Thanks for making this! (+2 questions)

### ISSUE THREAD

**Issue by haslam-forbes** [crs-k/stale-branches#972]
Hey @crs-k, just wanted to say thanks for making this GitHub action and the effort you put in to give it a clean interface. We had a bunch of dead branches in our company's repos and we wanted a clean way to notify authors that their branches were getting deleted before doing the actual deletion. Other actions didn't have the notification mechanism like this one, but this one fit the bill perfectly!

Two quick questions if you don't mind: 
1. We have some branches in our repos that are 1-2 years old. If we run the bot for the first time with content-delete permissions, will it automatically delete the branch immediately even before an issue is created? We would ideally like to post an issue on the 1st run, and then do the actual deletion on the 2nd run so that there's some time in between for the tagged author to handle the branch if needed.
2. If the author gets tagged and decides to delete the stale branch on his own, does the GitHub action automatically clean up after itself? (Otherwise it seems like the "STALE" issue that was created for that stale branch would now stick around forever since that stale branch no longer exists in the repo.)

**Comment by crs-k** [comment]
Hey there,

1. It requires and existing issue for deletion, so the branch should not be deleted until the second run. 

2. There's a function towards the end of the main routine that will close out orphaned issues. 

-Chris
